# This is a basic workflow to help you get started with Actions

name: nftlab-staging-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  builddeploy:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: './app/package-lock.json'

      - name: Set up .env files
        run: cp ./server/.env-staging ./server/.env && cp ./app/.env-staging ./app/.env
          
      - name: Install app deps
        working-directory: ./app
        run: npm ci

      - name: Build app
        working-directory: ./app
        run: npm run build

      - name: Install server deps
        working-directory: ./server
        run: npm ci      

      - name: Build server
        working-directory: ./server
        run: npm run build
      
      - name: Copy build artifacts
        run: rm -fr /build/nftlab && rsync -r --exclude "**/node_modules" ./* /build/nftlab
      

      
